/* Generated by JTB 1.4.7 */
package parser.visitor;

import parser.syntaxtree.*;
import java.util.*;

public class DepthFirstVoidArguVisitor<A> implements IVoidArguVisitor<A> {


  public void visit(final NodeChoice n, final A argu) {
    n.choice.accept(this, argu);
    return;
  }

  public void visit(final NodeList n, final A argu) {
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      e.next().accept(this, argu);
    }
    return;
  }

  public void visit(final NodeListOptional n, final A argu) {
    if (n.present()) {
      for (final Iterator<INode> e = n.elements(); e.hasNext();) {
        e.next().accept(this, argu);
        }
      return;
    } else
      return;
  }

  public void visit(final NodeOptional n, final A argu) {
    if (n.present()) {
      n.node.accept(this, argu);
      return;
    } else
      return;
  }

  public void visit(final NodeSequence n, final A argu) {
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      e.next().accept(this, argu);
    }
    return;
  }

  public void visit(final NodeTCF n, final A argu) {
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return;
  }

  public void visit(final NodeToken n, final A argu) {
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return;
  }

  public void visit(final Scope n, final A argu) {
    // f0 -> "SHEET "
    n.f0.accept(this, argu);
    // f1 -> <ID>
    n.f1.accept(this, argu);
    // f2 -> "{"
    n.f2.accept(this, argu);
    // f3 -> Declarations()
    n.f3.accept(this, argu);
    // f4 -> Essay()
    n.f4.accept(this, argu);
    // f5 -> "}"
    n.f5.accept(this, argu);
  }

  public void visit(final Declarations n, final A argu) {
    // f0 -> ( BeatDeclaration() )?
    n.f0.accept(this, argu);
    // f1 -> SpeedDeclaration()
    n.f1.accept(this, argu);
    // f2 -> InstrumentDeclaration()
    n.f2.accept(this, argu);
    // f3 -> VelocityDeclaration()
    n.f3.accept(this, argu);
    // f4 -> ( StropheDeclaration() )*
    n.f4.accept(this, argu);
  }

  public void visit(final BeatDeclaration n, final A argu) {
    // f0 -> "BEAT"
    n.f0.accept(this, argu);
    // f1 -> "="
    n.f1.accept(this, argu);
    // f2 -> <DIGIT>
    n.f2.accept(this, argu);
    // f3 -> "/"
    n.f3.accept(this, argu);
    // f4 -> ( %0 <SEMIBREVE>
    // .. .. | %1 <MINIM>
    // .. .. | %2 <CROTCHET>
    // .. .. | %3 <QUAVER>
    // .. .. | %4 <SEMIQUAVER>
    // .. .. | %5 <DEMISEMIQUAVER>
    // .. .. | %6 <HEMIDEMISEMIQUAVER> )
    n.f4.accept(this, argu);
    // f5 -> ";"
    n.f5.accept(this, argu);
  }

  public void visit(final VelocityDeclaration n, final A argu) {
    // f0 -> "VELOCITY"
    n.f0.accept(this, argu);
    // f1 -> "="
    n.f1.accept(this, argu);
    // f2 -> <INTEGER>
    n.f2.accept(this, argu);
    // f3 -> ";"
    n.f3.accept(this, argu);
  }

  public void visit(final SpeedDeclaration n, final A argu) {
    // f0 -> "SPEED"
    n.f0.accept(this, argu);
    // f1 -> "="
    n.f1.accept(this, argu);
    // f2 -> <INTEGER>
    n.f2.accept(this, argu);
    // f3 -> ";"
    n.f3.accept(this, argu);
  }

  public void visit(final InstrumentDeclaration n, final A argu) {
    // f0 -> "INSTRUMENT"
    n.f0.accept(this, argu);
    // f1 -> "="
    n.f1.accept(this, argu);
    // f2 -> <ID>
    n.f2.accept(this, argu);
    // f3 -> ";"
    n.f3.accept(this, argu);
  }

  public void visit(final StropheDeclaration n, final A argu) {
    // f0 -> "STROPHE"
    n.f0.accept(this, argu);
    // f1 -> <ID>
    n.f1.accept(this, argu);
    // f2 -> "{"
    n.f2.accept(this, argu);
    // f3 -> ( Sequence() )?
    n.f3.accept(this, argu);
    // f4 -> "}"
    n.f4.accept(this, argu);
  }

  public void visit(final Essay n, final A argu) {
    // f0 -> "ESSAY"
    n.f0.accept(this, argu);
    // f1 -> <ID>
    n.f1.accept(this, argu);
    // f2 -> "{"
    n.f2.accept(this, argu);
    // f3 -> ( Sequence() )?
    n.f3.accept(this, argu);
    // f4 -> "}"
    n.f4.accept(this, argu);
  }

  public void visit(final Sequence n, final A argu) {
    // f0 -> ( Notes() )+
    n.f0.accept(this, argu);
  }

  public void visit(final Notes n, final A argu) {
    // f0 -> . %0 Beat()
    // .. .. | %1 <ID>
    n.f0.accept(this, argu);
  }

  public void visit(final Beat n, final A argu) {
    // f0 -> ( Sign() )+
    n.f0.accept(this, argu);
    // f1 -> <ENDOFBEAT>
    n.f1.accept(this, argu);
  }

  public void visit(final Sign n, final A argu) {
    // f0 -> . %0 Group()
    // .. .. | %1 Single()
    n.f0.accept(this, argu);
  }

  public void visit(final Group n, final A argu) {
    // f0 -> "["
    n.f0.accept(this, argu);
    // f1 -> Note()
    n.f1.accept(this, argu);
    // f2 -> ( Others() )*
    n.f2.accept(this, argu);
    // f3 -> "]"
    n.f3.accept(this, argu);
    // f4 -> Flagged()
    n.f4.accept(this, argu);
  }

  public void visit(final Others n, final A argu) {
    // f0 -> ","
    n.f0.accept(this, argu);
    // f1 -> Note()
    n.f1.accept(this, argu);
  }

  public void visit(final Single n, final A argu) {
    // f0 -> ( %0 Note()
    // .. .. | %1 <SILENCE> )
    n.f0.accept(this, argu);
    // f1 -> Duration()
    n.f1.accept(this, argu);
  }

  public void visit(final Note n, final A argu) {
    // f0 -> ( <SEMITUNE> )?
    n.f0.accept(this, argu);
    // f1 -> <TUNE>
    n.f1.accept(this, argu);
  }

  public void visit(final Duration n, final A argu) {
    // f0 -> ( %0 Flagged()
    // .. .. | %1 Unflagged() )
    n.f0.accept(this, argu);
    // f1 -> ( <DOT> )?
    n.f1.accept(this, argu);
    // f2 -> ( Extend() )*
    n.f2.accept(this, argu);
  }

  public void visit(final Extend n, final A argu) {
    // f0 -> ( <CROSSBEAT> )?
    n.f0.accept(this, argu);
    // f1 -> ( %0 Flagged()
    // .. .. | %1 Unflagged() )
    n.f1.accept(this, argu);
    // f2 -> ( <DOT> )?
    n.f2.accept(this, argu);
  }

  public void visit(final Flagged n, final A argu) {
    // f0 -> . %0 <QUAVER>
    // .. .. | %1 <SEMIQUAVER>
    // .. .. | %2 <DEMISEMIQUAVER>
    // .. .. | %3 <HEMIDEMISEMIQUAVER>
    n.f0.accept(this, argu);
  }

  public void visit(final Unflagged n, final A argu) {
    // f0 -> . %0 <SEMIBREVE>
    // .. .. | %1 <MINIM>
    // .. .. | %2 <CROTCHET>
    n.f0.accept(this, argu);
  }

}
