/* Generated by JTB 1.4.7 */
package parser.visitor;

import parser.syntaxtree.*;

public interface IRetArguVisitor<R, A> {

  public R visit(final NodeChoice n, final A argu);

  public R visit(final NodeList n, final A argu);

  public R visit(final NodeListOptional n, final A argu);

  public R visit(final NodeOptional n, final A argu);

  public R visit(final NodeSequence n, final A argu);

  public R visit(final NodeTCF n, final A argu);

  public R visit(final NodeToken n, final A argu);

  public R visit(final Scope n, final A argu);

  public R visit(final Declarations n, final A argu);

  public R visit(final BeatDeclaration n, final A argu);

  public R visit(final VelocityDeclaration n, final A argu);

  public R visit(final SpeedDeclaration n, final A argu);

  public R visit(final InstrumentDeclaration n, final A argu);

  public R visit(final StropheDeclaration n, final A argu);

  public R visit(final Essay n, final A argu);

  public R visit(final Sequence n, final A argu);

  public R visit(final Notes n, final A argu);

  public R visit(final Beat n, final A argu);

  public R visit(final Sign n, final A argu);

  public R visit(final Group n, final A argu);

  public R visit(final Others n, final A argu);

  public R visit(final Single n, final A argu);

  public R visit(final Note n, final A argu);

  public R visit(final Duration n, final A argu);

  public R visit(final Extend n, final A argu);

  public R visit(final Flagged n, final A argu);

  public R visit(final Unflagged n, final A argu);

}
