/* Generated by JTB 1.4.7 */
package parser.visitor;

import parser.syntaxtree.*;

public interface IRetVisitor<R> {

  public R visit(final NodeChoice n);

  public R visit(final NodeList n);

  public R visit(final NodeListOptional n);

  public R visit(final NodeOptional n);

  public R visit(final NodeSequence n);

  public R visit(final NodeTCF n);

  public R visit(final NodeToken n);

  public R visit(final Scope n);

  public R visit(final Declarations n);

  public R visit(final BeatDeclaration n);

  public R visit(final VelocityDeclaration n);

  public R visit(final SpeedDeclaration n);

  public R visit(final InstrumentDeclaration n);

  public R visit(final StropheDeclaration n);

  public R visit(final Essay n);

  public R visit(final Sequence n);

  public R visit(final Notes n);

  public R visit(final Beat n);

  public R visit(final Sign n);

  public R visit(final Group n);

  public R visit(final Others n);

  public R visit(final Single n);

  public R visit(final Note n);

  public R visit(final Duration n);

  public R visit(final Extend n);

  public R visit(final Flagged n);

  public R visit(final Unflagged n);

}
