/* Generated by JTB 1.4.7 */
package parser.visitor;

import parser.syntaxtree.*;

public interface IVoidVisitor {

  public void visit(final NodeChoice n);

  public void visit(final NodeList n);

  public void visit(final NodeListOptional n);

  public void visit(final NodeOptional n);

  public void visit(final NodeSequence n);

  public void visit(final NodeTCF n);

  public void visit(final NodeToken n);

  public void visit(final Scope n);

  public void visit(final Declarations n);

  public void visit(final BeatDeclaration n);

  public void visit(final VelocityDeclaration n);

  public void visit(final SpeedDeclaration n);

  public void visit(final InstrumentDeclaration n);

  public void visit(final StropheDeclaration n);

  public void visit(final Essay n);

  public void visit(final Sequence n);

  public void visit(final Notes n);

  public void visit(final Beat n);

  public void visit(final Sign n);

  public void visit(final Group n);

  public void visit(final Others n);

  public void visit(final Single n);

  public void visit(final Note n);

  public void visit(final Duration n);

  public void visit(final Extend n);

  public void visit(final Flagged n);

  public void visit(final Unflagged n);

}
