/* Generated by JTB 1.4.7 */
package parser.syntaxtree;

import parser.visitor.*;

public class Declarations implements INode {

  public NodeOptional f0;

  public SpeedDeclaration f1;

  public InstrumentDeclaration f2;

  public VelocityDeclaration f3;

  public NodeListOptional f4;

  private static final long serialVersionUID = 147L;

  public Declarations(final NodeOptional n0, final SpeedDeclaration n1, final InstrumentDeclaration n2, final VelocityDeclaration n3, final NodeListOptional n4) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
