/* Generated by JTB 1.4.7 */
package parser.syntaxtree;

public class NodeTCF extends NodeToken {

  private static final long serialVersionUID = 147L;

  public NodeTCF(String s) {
    super(s, -1, -1, -1, -1, -1);
  }

  public NodeTCF(String s, final int kn, final int bl, final int bc, final int el, final int ec) {
    super(s, kn, bl, bc, el, ec);
  }

}
